In [1]:
import requests

url = 'http://openapi.seoul.go.kr:8088/59527456487368693834454c474a6c/json/SebcCollegeInfoKor/1/100/'

response = requests.get(url)
print(response.content)

b'{"SebcCollegeInfoKor":{"list_total_count":64,"RESULT":{"CODE":"INFO-000","MESSAGE":"\xec\xa0\x95\xec\x83\x81 \xec\xb2\x98\xeb\xa6\xac\xeb\x90\x98\xec\x97\x88\xec\x8a\xb5\xeb\x8b\x88\xeb\x8b\xa4"},"row":[{"MAIN_KEY":"BE_LiST23-0034","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x84\x9c\xec\x9a\xb8\xec\x8b\x9c\xeb\xa6\xbd\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xea\xb3\xb5\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xeb\x8f\x99\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac \xec\x84\x9c\xec\x9a\xb8\xec\x8b\x9c\xeb\xa6\xbd\xeb\x8c\x80\xeb\xa1\x9c 163 (\xec\xa0\x84\xeb\x86\x8d\xeb\x8f\x99 90\xeb\xb2\x88\xec\xa7\x80) ","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xeb\x8f\x99\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac","H_KOR_DONG":"\xed\x9c\x98\xea\xb2\xbd2\xeb\x8f\x99","TEL":"02-6490-6114","FAX":"02-2210-5576","HP":"http://www.uos.ac.kr"},{"MAIN_KEY":"BE_LiST23-0035","YEAR":"2013","CATE1_NAME":"\xec\xa0\x84\xeb\xac\xb8\xeb\x8c\x80\xed\x95\x99(3\xeb\x85\x84\xec\xa0\x9c)","NAME_KOR":"\xec\x84\x9c\xec\x9a\xb8\xec\x97\xac\xec\x9e\x90\xea\xb0\x84\xed\x98\xb8\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac \xed\x99\x8d\xec\xa0\x9c3\xeb\x8f\x99 \xec\x84\x9c\xec\x9a\xb8\xec\x97\xac\xec\x9e\x90\xea\xb0\x84\xed\x98\xb8\xeb\x8c\x80\xed\x95\x99","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac","H_KOR_DONG":"\xed\x99\x8d\xec\xa0\x9c2\xeb\x8f\x99","TEL":"02-2287-1700","FAX":"02-395-8018","HP":"http://www.snjc.ac.kr"},{"MAIN_KEY":"BE_LiST23-0036","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x84\x9c\xec\x9a\xb8\xec\x97\xac\xec\x9e\x90\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c \xeb\x85\xb8\xec\x9b\x90\xea\xb5\xac \xed\x99\x94\xeb\x9e\x91\xeb\xa1\x9c 621 \xec\x84\x9c\xec\x9a\xb8\xec\x97\xac\xec\x9e\x90\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xeb\x85\xb8\xec\x9b\x90\xea\xb5\xac","H_KOR_DONG":"\xea\xb3\xb5\xeb\xa6\x892\xeb\x8f\x99","TEL":"02-970-5114","FAX":"02-978-7931","HP":"http://www.swu.ac.kr"},{"MAIN_KEY":"BE_LiST23-0037","YEAR":"2013","CATE1_NAME":"\xec\xa0\x84\xeb\xac\xb8\xeb\x8c\x80\xed\x95\x99(2\xeb\x85\x84\xec\xa0\x9c)","NAME_KOR":"\xec\x84\x9c\xec\x9d\xbc\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xed\x95\x99\xea\xb5\x90\xeb\xaa\x85 \xeb\xb3\x80\xea\xb2\xbd","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\xa4\x91\xeb\x9e\x91\xea\xb5\xac \xec\x84\x9c\xec\x9d\xbc\xeb\x8c\x80\xed\x95\x99\xea\xb8\xb8 22(\xeb\xa9\xb4\xeb\xaa\xa9\xeb\x8f\x99 49-3) \xec\x84\x9c\xec\x9d\xbc\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\xa4\x91\xeb\x9e\x91\xea\xb5\xac","H_KOR_DONG":"\xeb\xa9\xb4\xeb\xaa\xa9\xec\xa0\x9c3.8\xeb\x8f\x99","TEL":"02-490-7300","FAX":"02-493-2576","HP":"http://www.seoil.ac.kr"},{"MAIN_KEY":"BE_LiST23-0038","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x84\xb1\xea\xb3\xb5\xed\x9a\x8c\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xea\xb5\xac\xeb\xa1\x9c\xea\xb5\xac \xed\x95\xad\xeb\x8f\x99 \xec\x84\xb1\xea\xb3\xb5\xed\x9a\x8c\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xea\xb5\xac\xeb\xa1\x9c\xea\xb5\xac","H_KOR_DONG":"\xec\x98\xa4\xeb\xa5\x982\xeb\x8f\x99","TEL":"02-2610-4142","FAX":"02-2610-4248","HP":"http://www.skhu.ac.kr"},{"MAIN_KEY":"BE_LiST23-0039","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x84\xb1\xea\xb7\xa0\xea\xb4\x80\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac \xeb\xaa\x85\xeb\xa5\x9c\xeb\x8f\x993\xea\xb0\x80 \xec\x84\xb1\xea\xb7\xa0\xea\xb4\x80\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac","H_KOR_DONG":"\xec\xa2\x85\xeb\xa1\x9c1.2.3.4\xea\xb0\x80\xeb\x8f\x99","TEL":"02-760-0114","FAX":"","HP":"http://www.skku.edu"},{"MAIN_KEY":"BE_LiST23-0040","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x84\xb1\xec\x8b\xa0\xec\x97\xac\xec\x9e\x90\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\x84\xb1\xeb\xb6\x81\xea\xb5\xac \xeb\x8f\x99\xec\x84\xa0\xeb\x8f\x993\xea\xb0\x80 \xec\x84\xb1\xec\x8b\xa0\xec\x97\xac\xec\x9e\x90\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\x84\xb1\xeb\xb6\x81\xea\xb5\xac","H_KOR_DONG":"\xeb\x8f\x99\xec\x84\xa0\xeb\x8f\x99","TEL":"02-920-7114","FAX":"02-920-2018","HP":"http://www.sungshin.ac.kr"},{"MAIN_KEY":"BE_LiST23-0041","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x84\xb8\xec\xa2\x85\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xea\xb4\x91\xec\xa7\x84\xea\xb5\xac \xea\xb5\xb0\xec\x9e\x90\xeb\x8f\x99 \xec\x84\xb8\xec\xa2\x85\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xea\xb4\x91\xec\xa7\x84\xea\xb5\xac","H_KOR_DONG":"\xea\xb5\xb0\xec\x9e\x90\xeb\x8f\x99","TEL":"02-3408-3114","FAX":"02-3408-3906","HP":"http://www.sejong.ac.kr"},{"MAIN_KEY":"BE_LiST23-0042","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x88\x99\xeb\xaa\x85\xec\x97\xac\xec\x9e\x90\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\x9a\xa9\xec\x82\xb0\xea\xb5\xac \xec\xb2\xad\xed\x8c\x8c\xeb\xa1\x9c47\xea\xb8\xb8 100 \xec\x88\x99\xeb\xaa\x85\xec\x97\xac\xec\x9e\x90\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\x9a\xa9\xec\x82\xb0\xea\xb5\xac","H_KOR_DONG":"\xec\xb2\xad\xed\x8c\x8c\xeb\x8f\x99","TEL":"","FAX":"","HP":"http://www.sookmyung.ac.kr/"},{"MAIN_KEY":"BE_LiST23-0043","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x88\xad\xec\x8b\xa4\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xeb\x8f\x99\xec\x9e\x91\xea\xb5\xac \xec\x83\x81\xeb\x8f\x84\xeb\x8f\x99 511 \xec\x88\xad\xec\x8b\xa4\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xeb\x8f\x99\xec\x9e\x91\xea\xb5\xac","H_KOR_DONG":"\xec\x83\x81\xeb\x8f\x841\xeb\x8f\x99","TEL":"02-820-0114","FAX":"","HP":"http://www.ssu.ac.kr"},{"MAIN_KEY":"BE_LiST23-0044","YEAR":"2013","CATE1_NAME":"\xec\xa0\x84\xeb\xac\xb8\xeb\x8c\x80\xed\x95\x99(2\xeb\x85\x84\xec\xa0\x9c)","NAME_KOR":"\xec\x88\xad\xec\x9d\x98\xec\x97\xac\xec\x9e\x90\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c \xec\xa4\x91\xea\xb5\xac \xec\x86\x8c\xed\x8c\x8c\xeb\xa1\x9c2\xea\xb8\xb8 10(\xec\x98\x88\xec\x9e\xa5\xeb\x8f\x99)","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\xa4\x91\xea\xb5\xac","H_KOR_DONG":"\xed\x95\x84\xeb\x8f\x99","TEL":"02-3708-9000","FAX":"02-773-2625","HP":"http://www.sewc.ac.kr"},{"MAIN_KEY":"BE_LiST23-0045","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x97\xb0\xec\x84\xb8\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac \xec\x8b\xa0\xec\xb4\x8c\xeb\x8f\x99 \xec\x97\xb0\xec\x84\xb8\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac","H_KOR_DONG":"\xec\x8b\xa0\xec\xb4\x8c\xeb\x8f\x99","TEL":"02-2123-2114","FAX":"02-392-0618","HP":"http://www.yonsei.ac.kr"},{"MAIN_KEY":"BE_LiST23-0046","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x9d\xb4\xed\x99\x94\xec\x97\xac\xec\x9e\x90\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac \xeb\x8c\x80\xed\x98\x84\xeb\x8f\x99 11-1 \xec\x9d\xb4\xed\x99\x94\xec\x97\xac\xec\x9e\x90\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac","H_KOR_DONG":"\xec\x8b\xa0\xec\xb4\x8c\xeb\x8f\x99","TEL":"02-3277-2114","FAX":"02-393-5903","HP":"http://www.ewha.ac.kr"},{"MAIN_KEY":"BE_LiST23-0047","YEAR":"2013","CATE1_NAME":"\xec\xa0\x84\xeb\xac\xb8\xeb\x8c\x80\xed\x95\x99(2\xeb\x85\x84\xec\xa0\x9c)","NAME_KOR":"\xec\x9d\xb8\xeb\x8d\x95\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xeb\x85\xb8\xec\x9b\x90\xea\xb5\xac \xec\xb4\x88\xec\x95\x88\xec\x82\xb0\xeb\xa1\x9c 12","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xeb\x85\xb8\xec\x9b\x90\xea\xb5\xac","H_KOR_DONG":"\xec\x9b\x94\xea\xb3\x842\xeb\x8f\x99","TEL":"02-950-7000","FAX":"02-906-5340","HP":"http://www.induk.ac.kr"},{"MAIN_KEY":"BE_LiST23-0048","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\x9e\xa5\xeb\xa1\x9c\xed\x9a\x8c\xec\x8b\xa0\xed\x95\x99\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xea\xb4\x91\xec\xa7\x84\xea\xb5\xac \xea\xb4\x91\xec\x9e\xa5\xeb\xa1\x9c 5\xea\xb8\xb8 25-1(\xea\xb4\x91\xec\x9e\xa5\xeb\x8f\x99) \xec\x9e\xa5\xeb\xa1\x9c\xed\x9a\x8c\xec\x8b\xa0\xed\x95\x99\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xea\xb4\x91\xec\xa7\x84\xea\xb5\xac","H_KOR_DONG":"\xea\xb4\x91\xec\x9e\xa5\xeb\x8f\x99","TEL":"02-450-0700","FAX":"","HP":"http://www.pcts.ac.kr"},{"MAIN_KEY":"BE_LiST23-0049","YEAR":"2013","CATE1_NAME":"\xec\xa0\x84\xeb\xac\xb8\xeb\x8c\x80\xed\x95\x99(3\xeb\x85\x84\xec\xa0\x9c)","NAME_KOR":"\xec\xa0\x81\xec\x8b\xad\xec\x9e\x90\xea\xb0\x84\xed\x98\xb8\xeb\x8c\x80\xed\x95\x99","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xed\x8f\x90\xea\xb5\x90","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac \xea\xb2\xbd\xea\xb5\x90\xec\x9e\xa5\xea\xb8\xb88","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac","H_KOR_DONG":"\xea\xb5\x90\xeb\x82\xa8\xeb\x8f\x99","TEL":"02-3700-3600","FAX":"02-3700-3400","HP":"http://redcross.cau.ac.kr"},{"MAIN_KEY":"BE_LiST23-0050","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\xa4\x91\xec\x95\x99\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90 \xec\x84\x9c\xec\x9a\xb8\xec\xba\xa0\xed\x8d\xbc\xec\x8a\xa4","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xeb\x8f\x99\xec\x9e\x91\xea\xb5\xac \xed\x9d\x91\xec\x84\x9d\xeb\xa1\x9c 84","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xeb\x8f\x99\xec\x9e\x91\xea\xb5\xac","H_KOR_DONG":"\xed\x9d\x91\xec\x84\x9d\xeb\x8f\x99","TEL":"02-820-5114","FAX":"","HP":"http://www.cau.ac.kr"},{"MAIN_KEY":"BE_LiST23-0051","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\xb4\x9d\xec\x8b\xa0\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xeb\x8f\x99\xec\x9e\x91\xea\xb5\xac \xec\x82\xac\xeb\x8b\xb9\xeb\x8f\x99 \xec\x82\xb031-3","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xeb\x8f\x99\xec\x9e\x91\xea\xb5\xac","H_KOR_DONG":"\xec\x82\xac\xeb\x8b\xb93\xeb\x8f\x99","TEL":"02-3479-0200","FAX":"02-536-2602","HP":"http://www.chongshin.ac.kr"},{"MAIN_KEY":"BE_LiST23-0052","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xec\xb6\x94\xea\xb3\x84\xec\x98\x88\xec\x88\xa0\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac \xeb\xb6\x81\xec\x95\x84\xed\x98\x84\xeb\x8f\x99 190-1 \xec\xb6\x94\xea\xb3\x84\xec\x98\x88\xec\x88\xa0\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\x84\x9c\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac","H_KOR_DONG":"\xec\xb6\xa9\xed\x98\x84\xeb\x8f\x99","TEL":"02-362-5700","FAX":"02-392-1777","HP":"http://www.chugye.ac.kr"},{"MAIN_KEY":"BE_LiST23-0053","YEAR":"2013","CATE1_NAME":"\xeb\xb0\xa9\xec\x86\xa1\xed\x86\xb5\xec\x8b\xa0\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xed\x95\x9c\xea\xb5\xad\xeb\xb0\xa9\xec\x86\xa1\xed\x86\xb5\xec\x8b\xa0\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xea\xb5\xad\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac \xeb\x8f\x99\xec\x88\xad\xeb\x8f\x99 \xed\x95\x9c\xea\xb5\xad\xeb\xb0\xa9\xec\x86\xa1\xed\x86\xb5\xec\x8b\xa0\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\xa2\x85\xeb\xa1\x9c\xea\xb5\xac","H_KOR_DONG":"\xec\x9d\xb4\xed\x99\x94\xeb\x8f\x99","TEL":"02-3668-4114","FAX":"02-744-5882","HP":"http://www.knou.ac.kr"},{"MAIN_KEY":"BE_LiST23-0054","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xed\x95\x9c\xea\xb5\xad\xec\x84\xb1\xec\x84\x9c\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xeb\x85\xb8\xec\x9b\x90\xea\xb5\xac \xec\x83\x81\xea\xb3\x847\xeb\x8f\x99 \xed\x95\x9c\xea\xb5\xad\xec\x84\xb1\xec\x84\x9c\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xeb\x85\xb8\xec\x9b\x90\xea\xb5\xac","H_KOR_DONG":"\xec\x83\x81\xea\xb3\x846.7\xeb\x8f\x99","TEL":"02-950-5401","FAX":"02-950-5411","HP":"http://www.bible.ac.kr"},{"MAIN_KEY":"BE_LiST23-0055","YEAR":"2013","CATE1_NAME":"\xea\xb0\x81\xec\xa2\x85\xeb\x8c\x80\xed\x95\x99(\xeb\x8c\x80\xed\x95\x99)","NAME_KOR":"\xed\x95\x9c\xea\xb5\xad\xec\x98\x88\xec\x88\xa0\xec\xa2\x85\xed\x95\xa9\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xed\x8a\xb9\xeb\xb3\x84\xeb\xb2\x95\xea\xb5\xad\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\x84\xb1\xeb\xb6\x81\xea\xb5\xac \xec\x84\x9d\xea\xb4\x80\xeb\x8f\x99 ","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\x84\xb1\xeb\xb6\x81\xea\xb5\xac","H_KOR_DONG":"\xec\x84\x9d\xea\xb4\x80\xeb\x8f\x99","TEL":"","FAX":"","HP":""},{"MAIN_KEY":"BE_LiST23-0056","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xed\x95\x9c\xea\xb5\xad\xec\x99\xb8\xea\xb5\xad\xec\x96\xb4\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xeb\x8f\x99\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac \xec\x9d\xb4\xeb\xac\xb8\xeb\xa1\x9c 107","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xeb\x8f\x99\xeb\x8c\x80\xeb\xac\xb8\xea\xb5\xac","H_KOR_DONG":"\xec\x9d\xb4\xeb\xac\xb81\xeb\x8f\x99","TEL":"02-2173-2114","FAX":"","HP":"http://www.hufs.ac.kr"},{"MAIN_KEY":"BE_LiST23-0057","YEAR":"2013","CATE1_NAME":"\xec\x9d\xbc\xeb\xb0\x98\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xed\x95\x9c\xea\xb5\xad\xec\xb2\xb4\xec\x9c\xa1\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xea\xb5\xad\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xec\x86\xa1\xed\x8c\x8c\xea\xb5\xac \xec\x98\xa4\xeb\xa5\x9c\xeb\x8f\x99 \xed\x95\x9c\xea\xb5\xad\xec\xb2\xb4\xec\x9c\xa1\xeb\x8c\x80\xed\x95\x99\xea\xb5\x90","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xec\x86\xa1\xed\x8c\x8c\xea\xb5\xac","H_KOR_DONG":"\xec\x98\xa4\xeb\xa5\x9c\xeb\x8f\x99","TEL":"02-410-6564","FAX":"02-410-6569","HP":"http://www.knsu.ac.kr/"},{"MAIN_KEY":"BE_LiST23-0058","YEAR":"2013","CATE1_NAME":"\xea\xb8\xb0\xeb\x8a\xa5\xeb\x8c\x80\xed\x95\x99","NAME_KOR":"\xed\x95\x9c\xea\xb5\xad\xed\x8f\xb4\xeb\xa6\xac\xed\x85\x8d I \xeb\x8c\x80\xed\x95\x99 \xec\x84\x9c\xec\x9a\xb8\xea\xb0\x95\xec\x84\x9c\xec\xba\xa0\xed\x8d\xbc\xec\x8a\xa4","BRANCH":"\xeb\xb3\xb8\xea\xb5\x90","STATE":"\xea\xb8\xb0\xec\xa1\xb4","TYPE":"\xec\x82\xac\xeb\xa6\xbd","POSTCODE":"","ADD_KOR":"\xec\x84\x9c\xec\x9a\xb8 \xea\xb0\x95\xec\x84\x9c\xea\xb5\xac \xed\x99\x94\xea\xb3\xa1\xeb\x8f\x99 \xec\x82\xb060-1","ADD_KOR_ROAD":"","H_KOR_CITY":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c","H_KOR_GU":"\xea\xb0\x95\xec\x84\x9c\xea\xb5\xac","H_KOR_DONG":"\xec\x9a\xb0\xec\x9e\xa5\xec\x82\xb0\xeb\x8f\x99","TEL":"02-2186-5800","FAX":"02-2186-5819","HP":"http://kangseo.kopo.ac.kr"},{"MAIN_KEY":"BE_LiST23-0059","YEAR":"2013","CATE1_NAME":"\xea\xb8\xb0\xeb\x8a\xa5\xeb\x8c\x80\xed\x

In [2]:
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
data = response.json()

In [4]:
data

{'SebcCollegeInfoKor': {'list_total_count': 64,
  'RESULT': {'CODE': 'INFO-000', 'MESSAGE': '정상 처리되었습니다'},
  'row': [{'MAIN_KEY': 'BE_LiST23-0034',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '서울시립대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '공립',
    'POSTCODE': '',
    'ADD_KOR': '서울 동대문구 서울시립대로 163 (전농동 90번지) ',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '동대문구',
    'H_KOR_DONG': '휘경2동',
    'TEL': '02-6490-6114',
    'FAX': '02-2210-5576',
    'HP': 'http://www.uos.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0035',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(3년제)',
    'NAME_KOR': '서울여자간호대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서대문구 홍제3동 서울여자간호대학',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '홍제2동',
    'TEL': '02-2287-1700',
    'FAX': '02-395-8018',
    'HP': 'http://www.snjc.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0036',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '서울여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울특별시 노원구 화랑로 621 서울여자대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '노원구',
    'H_KOR_DONG': '공릉2동',
    'TEL': '02-970-5114',
    'FAX': '02-978-7931',
    'HP': 'http://www.swu.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0037',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(2년제)',
    'NAME_KOR': '서일대학교',
    'BRANCH': '본교',
    'STATE': '학교명 변경',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 중랑구 서일대학길 22(면목동 49-3) 서일대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '중랑구',
    'H_KOR_DONG': '면목제3.8동',
    'TEL': '02-490-7300',
    'FAX': '02-493-2576',
    'HP': 'http://www.seoil.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0038',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '성공회대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 구로구 항동 성공회대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '구로구',
    'H_KOR_DONG': '오류2동',
    'TEL': '02-2610-4142',
    'FAX': '02-2610-4248',
    'HP': 'http://www.skhu.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0039',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '성균관대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 종로구 명륜동3가 성균관대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '종로구',
    'H_KOR_DONG': '종로1.2.3.4가동',
    'TEL': '02-760-0114',
    'FAX': '',
    'HP': 'http://www.skku.edu'},
   {'MAIN_KEY': 'BE_LiST23-0040',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '성신여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 성북구 동선동3가 성신여자대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성북구',
    'H_KOR_DONG': '동선동',
    'TEL': '02-920-7114',
    'FAX': '02-920-2018',
    'HP': 'http://www.sungshin.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0041',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '세종대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 광진구 군자동 세종대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '광진구',
    'H_KOR_DONG': '군자동',
    'TEL': '02-3408-3114',
    'FAX': '02-3408-3906',
    'HP': 'http://www.sejong.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0042',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '숙명여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 용산구 청파로47길 100 숙명여자대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '용산구',
    'H_KOR_DONG': '청파동',
    'TEL': '',
    'FAX': '',
    'HP': 'http://www.sookmyung.ac.kr/'},
   {'MAIN_KEY': 'BE_LiST23-0043',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '숭실대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 동작구 상도동 511 숭실대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '동작구',
    'H_KOR_DONG': '상도1동',
    'TEL': '02-820-0114',
    'FAX': '',
    'HP': 'http://www.ssu.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0044',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(2년제)',
    'NAME_KOR': '숭의여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울특별시 중구 소파로2길 10(예장동)',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '중구',
    'H_KOR_DONG': '필동',
    'TEL': '02-3708-9000',
    'FAX': '02-773-2625',
    'HP': 'http://www.sewc.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0045',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '연세대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서대문구 신촌동 연세대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '신촌동',
    'TEL': '02-2123-2114',
    'FAX': '02-392-0618',
    'HP': 'http://www.yonsei.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0046',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '이화여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서대문구 대현동 11-1 이화여자대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '신촌동',
    'TEL': '02-3277-2114',
    'FAX': '02-393-5903',
    'HP': 'http://www.ewha.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0047',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(2년제)',
    'NAME_KOR': '인덕대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 노원구 초안산로 12',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '노원구',
    'H_KOR_DONG': '월계2동',
    'TEL': '02-950-7000',
    'FAX': '02-906-5340',
    'HP': 'http://www.induk.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0048',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '장로회신학대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 광진구 광장로 5길 25-1(광장동) 장로회신학대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '광진구',
    'H_KOR_DONG': '광장동',
    'TEL': '02-450-0700',
    'FAX': '',
    'HP': 'http://www.pcts.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0049',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(3년제)',
    'NAME_KOR': '적십자간호대학',
    'BRANCH': '본교',
    'STATE': '폐교',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 종로구 경교장길8',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '종로구',
    'H_KOR_DONG': '교남동',
    'TEL': '02-3700-3600',
    'FAX': '02-3700-3400',
    'HP': 'http://redcross.cau.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0050',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '중앙대학교 서울캠퍼스',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 동작구 흑석로 84',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '동작구',
    'H_KOR_DONG': '흑석동',
    'TEL': '02-820-5114',
    'FAX': '',
    'HP': 'http://www.cau.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0051',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '총신대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 동작구 사당동 산31-3',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '동작구',
    'H_KOR_DONG': '사당3동',
    'TEL': '02-3479-0200',
    'FAX': '02-536-2602',
    'HP': 'http://www.chongshin.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0052',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '추계예술대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서대문구 북아현동 190-1 추계예술대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '충현동',
    'TEL': '02-362-5700',
    'FAX': '02-392-1777',
    'HP': 'http://www.chugye.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0053',
    'YEAR': '2013',
    'CATE1_NAME': '방송통신대학',
    'NAME_KOR': '한국방송통신대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '국립',
    'POSTCODE': '',
    'ADD_KOR': '서울 종로구 동숭동 한국방송통신대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '종로구',
    'H_KOR_DONG': '이화동',
    'TEL': '02-3668-4114',
    'FAX': '02-744-5882',
    'HP': 'http://www.knou.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0054',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '한국성서대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 노원구 상계7동 한국성서대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '노원구',
    'H_KOR_DONG': '상계6.7동',
    'TEL': '02-950-5401',
    'FAX': '02-950-5411',
    'HP': 'http://www.bible.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0055',
    'YEAR': '2013',
    'CATE1_NAME': '각종대학(대학)',
    'NAME_KOR': '한국예술종합학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '특별법국립',
    'POSTCODE': '',
    'ADD_KOR': '서울 성북구 석관동 ',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성북구',
    'H_KOR_DONG': '석관동',
    'TEL': '',
    'FAX': '',
    'HP': ''},
   {'MAIN_KEY': 'BE_LiST23-0056',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '한국외국어대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 동대문구 이문로 107',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '동대문구',
    'H_KOR_DONG': '이문1동',
    'TEL': '02-2173-2114',
    'FAX': '',
    'HP': 'http://www.hufs.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0057',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '한국체육대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '국립',
    'POSTCODE': '',
    'ADD_KOR': '서울 송파구 오륜동 한국체육대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '송파구',
    'H_KOR_DONG': '오륜동',
    'TEL': '02-410-6564',
    'FAX': '02-410-6569',
    'HP': 'http://www.knsu.ac.kr/'},
   {'MAIN_KEY': 'BE_LiST23-0058',
    'YEAR': '2013',
    'CATE1_NAME': '기능대학',
    'NAME_KOR': '한국폴리텍 I 대학 서울강서캠퍼스',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 강서구 화곡동 산60-1',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '강서구',
    'H_KOR_DONG': '우장산동',
    'TEL': '02-2186-5800',
    'FAX': '02-2186-5819',
    'HP': 'http://kangseo.kopo.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0059',
    'YEAR': '2013',
    'CATE1_NAME': '기능대학',
    'NAME_KOR': '한국폴리텍Ⅰ대학 서울정수캠퍼스',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 용산구 보광로 73(보광동 238)',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '용산구',
    'H_KOR_DONG': '보광동',
    'TEL': '02-2001-4000',
    'FAX': '02-2001-4119',
    'HP': 'http://jungsu.kopo.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0060',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '한성대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 성북구 삼선동3가 389 한성대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성북구',
    'H_KOR_DONG': '삼선동',
    'TEL': '02-760-4231',
    'FAX': '02-745-8943',
    'HP': 'http://www.hansung.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0061',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '한양대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울특별시 성동구 왕십리로 222 ',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성동구',
    'H_KOR_DONG': '사근동',
    'TEL': '02-2220-0114',
    'FAX': '',
    'HP': 'http://www.hanyang.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0062',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(2년제)',
    'NAME_KOR': '한양여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 성동구 행당동 살곶이길 200',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성동구',
    'H_KOR_DONG': '사근동',
    'TEL': '02-2290-2114',
    'FAX': '02-2291-6111',
    'HP': 'http://www.hywoman.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0063',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '한영신학대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 구로구 경인로 290-42  한영신학대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '구로구',
    'H_KOR_DONG': '개봉1동',
    'TEL': '02-2067-4500',
    'FAX': '02-2616-4102',
    'HP': 'http://www.hytu.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0064',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '홍익대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울특별시 마포구 와우산로 94(상수동)',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '마포구',
    'H_KOR_DONG': '서강동',
    'TEL': '02-320-1114',
    'FAX': '02-320-1122',
    'HP': 'http://www.hongik.ac.kr/'},
   {'MAIN_KEY': 'BE_LiST23-0001',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '가톨릭대학교',
    'BRANCH': '제2캠퍼스',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서초구 반포동 505',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서초구',
    'H_KOR_DONG': '반포4동',
    'TEL': '',
    'FAX': '',
    'HP': 'http://songeui.catholic.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0002',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '가톨릭대학교',
    'BRANCH': '제3캠퍼스',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 종로구 창경궁로 296-12(혜화동) ',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '종로구',
    'H_KOR_DONG': '이화동',
    'TEL': '02-740-9714',
    'FAX': '02-741-2801',
    'HP': 'http://catholic.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0003',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '감리교신학대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서대문구 냉천동 감리교신학대학',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '천연동',
    'TEL': '02-361-9114',
    'FAX': '02-361-9299',
    'HP': 'http://www.mtu.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0004',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '건국대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 광진구 화양동',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '광진구',
    'H_KOR_DONG': '화양동',
    'TEL': '02-450-3114',
    'FAX': '02-450-4126',
    'HP': 'http://www.konkuk.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0005',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '경기대학교',
    'BRANCH': '제2캠퍼스',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서대문구 경기대로9길 24 경기대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '충현동',
    'TEL': '02-390-5114',
    'FAX': '031-249-8718',
    'HP': 'http://www.kyonggi.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0006',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '경희대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 동대문구 회기동 경희대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '동대문구',
    'H_KOR_DONG': '회기동',
    'TEL': '02-961-0114',
    'FAX': '02-961-0930',
    'HP': 'http://www.khu.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0007',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '고려대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 성북구 안암동 고려대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성북구',
    'H_KOR_DONG': '안암동',
    'TEL': '02-3290-1114',
    'FAX': '',
    'HP': 'http://www.korea.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0008',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '광운대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울특별시 노원구 월계동 447-1',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '노원구',
    'H_KOR_DONG': '월계1동',
    'TEL': '',
    'FAX': '',
    'HP': 'http://www.kw.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0009',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '국민대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 성북구 정릉3동 국민대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성북구',
    'H_KOR_DONG': '정릉3동',
    'TEL': '02-910-4114',
    'FAX': '',
    'HP': 'http://www.kookmin.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0010',
    'YEAR': '2013',
    'CATE1_NAME': '전공대학',
    'NAME_KOR': '국제예술대학',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 강남구 논현동 79',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '강남구',
    'H_KOR_DONG': '논현2동',
    'TEL': '02-542-8197',
    'FAX': '02-517-1392',
    'HP': 'http://www.kica.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0011',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '그리스도대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 강서구 화곡6동 그리스도대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '강서구',
    'H_KOR_DONG': '화곡본동',
    'TEL': '02-2600-2400',
    'FAX': '02-2698-8876',
    'HP': 'http://kcu.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0012',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '덕성여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울특별시 도봉구 삼양로 144길 33',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '도봉구',
    'H_KOR_DONG': '쌍문1동',
    'TEL': '02-901-8000',
    'FAX': '',
    'HP': 'http://www.duksung.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0013',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '동국대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 중구 필동3가 동국대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '중구',
    'H_KOR_DONG': '필동',
    'TEL': '02-2260-3114',
    'FAX': '02-2277-1274',
    'HP': 'http://www.dongguk.edu'},
   {'MAIN_KEY': 'BE_LiST23-0014',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '동덕여자대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 성북구 하월곡2동 동덕여자대학교',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '성북구',
    'H_KOR_DONG': '삼선동',
    'TEL': '02-940-4000',
    'FAX': '02-940-4182',
    'HP': 'http://www.dongduk.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0015',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(3년제)',
    'NAME_KOR': '동양미래대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울시 구로구 경인로 445 동양미래대학교 (고척동 62-160)',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '구로구',
    'H_KOR_DONG': '고척1동',
    'TEL': '02-2610-1700',
    'FAX': '02-2688-5494',
    'HP': 'http://www.dongyang.ac.kr/'},
   {'MAIN_KEY': 'BE_LiST23-0016',
    'YEAR': '2013',
    'CATE1_NAME': '사이버대학(대학)',
    'NAME_KOR': '디지털서울문화예술대학교',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울시 서대문구 통일로 37길 60 (홍제동 318-18)',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '홍제1동',
    'TEL': '02-2287-0222',
    'FAX': '02-379-8828',
    'HP': 'http://www.scau.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0017',
    'YEAR': '2013',
    'CATE1_NAME': '일반대학',
    'NAME_KOR': '명지대학교 인문캠퍼스',
    'BRANCH': '제2캠퍼스',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',
    'ADD_KOR': '서울 서대문구 남가좌동 50-3',
    'ADD_KOR_ROAD': '',
    'H_KOR_CITY': '서울특별시',
    'H_KOR_GU': '서대문구',
    'H_KOR_DONG': '남가좌2동',
    'TEL': '02-300-1556',
    'FAX': '02-300-1556',
    'HP': 'http://www.mju.ac.kr'},
   {'MAIN_KEY': 'BE_LiST23-0018',
    'YEAR': '2013',
    'CATE1_NAME': '전문대학(3년제)',
    'NAME_KOR': '명지전문대학',
    'BRANCH': '본교',
    'STATE': '기존',
    'TYPE': '사립',
    'POSTCODE': '',

In [5]:
temp = []
for d in data['SebcCollegeInfoKor']['row']:
  temp.append(d)
uni = pd.DataFrame(temp)
uni

,MAIN_KEY,YEAR,CATE1_NAME,NAME_KOR,BRANCH,STATE,TYPE,POSTCODE,ADD_KOR,ADD_KOR_ROAD,H_KOR_CITY,H_KOR_GU,H_KOR_DONG,TEL,FAX,HP
0,BE_LiST23-0034,2013,일반대학,서울시립대학교,본교,기존,공립,,서울 동대문구 서울시립대로 163 (전농동 90번지),,서울특별시,동대문구,휘경2동,02-6490-6114,02-2210-5576,http://www.uos.ac.kr
1,BE_LiST23-0035,2013,전문대학(3년제),서울여자간호대학교,본교,기존,사립,,서울 서대문구 홍제3동 서울여자간호대학,,서울특별시,서대문구,홍제2동,02-2287-1700,02-395-8018,http://www.snjc.ac.kr
2,BE_LiST23-0036,2013,일반대학,서울여자대학교,본교,기존,사립,,서울특별시 노원구 화랑로 621 서울여자대학교,,서울특별시,노원구,공릉2동,02-970-5114,02-978-7931,http://www.swu.ac.kr
3,BE_LiST23-0037,2013,전문대학(2년제),서일대학교,본교,학교명 변경,사립,,서울 중랑구 서일대학길 22(면목동 49-3) 서일대학교,,서울특별시,중랑구,면목제3.8동,02-490-7300,02-493-2576,http://www.seoil.ac.kr
4,BE_LiST23-0038,2013,일반대학,성공회대학교,본교,기존,사립,,서울 구로구 항동 성공회대학교,,서울특별시,구로구,오류2동,02-2610-4142,02-2610-4248,http://www.skhu.ac.kr
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,BE_LiST23-0029,2013,교육대학,서울교육대학교,본교,기존,국립,,서울 서초구 서초중앙로 96(서초동 1650),,서울특별시,서초구,서초1동,02-3475-2114,02-581-7711,http://www.snue.ac.kr
60,BE_LiST23-0030,2013,일반대학,서울기독대학교,본교,기존,사립,,서울 은평구 갈현로 4길 26-2호,,서울특별시,은평구,신사1동,02-380-2500,02-380-2535,http://www.scu.ac.kr
61,BE_LiST23-0031,2013,일반대학,서울대학교,본교,기존,국립대법인,,서울 관악구 관악로 1 서울대학교,,서울특별시,관악구,낙성대동,02-880-5114,02-885-5272,http://www.snu.ac.kr
62,BE_LiST23-0032,2013,사이버대학(대학),서울디지털대학교,본교,기존,사립,,서울 마포구 도화동 560번지,,서울특별시,마포구,도화동,02-1644-0982,02-2128-3006,http://www.sdu.ac.kr
63,BE_LiST23-0033,2013,사이버대학(대학),서울사이버대학교,본교,기존,사립,,서울 강북구 솔매로49길 60(미아동 193-15) 서울사이버대학교,,서울특별시,강북구,미아동,02-944-5000,02-980-2222,http://www.iscu.ac.kr

In [21]:
url = 'http://openapi.seoul.go.kr:8088/59527456487368693834454c474a6c/json/tbEntranceItem/1/100/'
# 보건소 데이터
response = requests.get(url)

data = response.json()
data

{'tbEntranceItem': {'list_total_count': 3606,
  'RESULT': {'CODE': 'INFO-000', 'MESSAGE': '정상 처리되었습니다'},
  'row': [{'ID': '3007',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0877',
    'FCLT_NM': '꿈동산어린이공원',
    'LAT': 37.650288,
    'LOT': 127.03686,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '서울특별시 도봉구 도봉로110나길 99',
    'LOTNO_ADDR': '서울특별시 도봉구 창동 663-1',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 5914 6130',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '3008',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0878',
    'FCLT_NM': '미화어린이공원',
    'LAT': 37.654945,
    'LOT': 127.03969,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '서울특별시 도봉구 도봉로 564',
    'LOTNO_ADDR': '서울특별시 도봉구 창동 715-17',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 5939 6181',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '3009',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0879',
    'FCLT_NM': '꿈동산어린이공원',
    'LAT': 37.57329,
    'LOT': 127.04584,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '서울특별시 동대문구 황물로 42',
    'LOTNO_ADDR': '서울특별시 동대문구 답십리동 1002-1',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 5989 5275',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '3010',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0880',
    'FCLT_NM': '새움어린이공원',
    'LAT': 37.57076,
    'LOT': 127.048676,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '서울특별시 동대문구 천호대로55길 11',
    'LOTNO_ADDR': '서울특별시 동대문구 답십리동 1009-1',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 6014 5247',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '3012',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0882',
    'FCLT_NM': '동산어린이공원',
    'LAT': 37.566967,
    'LOT': 127.05754,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '서울특별시 동대문구 전농로2나길 7',
    'LOTNO_ADDR': '서울특별시 동대문구 답십리동 998-1',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 6092 5204',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '3013',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0883',
    'FCLT_NM': '우산각어린이공원',
    'LAT': 37.57345,
    'LOT': 127.02443,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '서울특별시 동대문구 천호대로4길 22',
    'LOTNO_ADDR': '서울특별시 동대문구 신설동 109-4',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 5800 5278',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '31',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'B0031',
    'FCLT_NM': '주양쇼핑',
    'LAT': 37.55252,
    'LOT': 127.153496,
    'BLDN_CLNY_YN': 'BG_AB',
    'FCLT_USG_SE': 'FU_BA',
    'RDN_ADDR': '서울특별시 강동구 고덕로62길 55',
    'LOTNO_ADDR': '서울특별시 강동구 명일동 48',
    'ETC': '공사중',
    'NTN_BRNCH_NO': '다사 6939 5040',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '308',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'B0308',
    'FCLT_NM': '에이피엠 플레이스',
    'LAT': 37.565273,
    'LOT': 127.00841,
    'BLDN_CLNY_YN': 'BG_AB',
    'FCLT_USG_SE': 'FU_BA',
    'RDN_ADDR': '서울특별시 중구 을지로 276',
    'LOTNO_ADDR': '서울특별시 중구 을지로7가 105',
    'ETC': '라모도쇼핑몰이 에이피엠 플레이스로 변경됨',
    'NTN_BRNCH_NO': '다사 5658 5188',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2177',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0047',
    'FCLT_NM': '강일공원',
    'LAT': 37.56955,
    'LOT': 127.17451,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '서울특별시 강동구 아리수로97길 68',
    'LOTNO_ADDR': '서울특별시 강동구 강일동 332-5',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 7125 5229',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2179',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0049',
    'FCLT_NM': '능골근린공원',
    'LAT': 37.556427,
    'LOT': 127.174545,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '',
    'LOTNO_ADDR': '서울특별시 강동구 상일동 536',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 7125 5083',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2180',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0050',
    'FCLT_NM': '벌말공원',
    'LAT': 37.560326,
    'LOT': 127.17666,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '서울특별시 강동구 아리수로94길 72',
    'LOTNO_ADDR': '서울특별시 강동구 강일동 700',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 7144 5126',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2184',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0054',
    'FCLT_NM': '동명공원',
    'LAT': 37.561466,
    'LOT': 127.16493,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '서울특별시 강동구 아리수로78길 23',
    'LOTNO_ADDR': '서울특별시 강동구 고덕동 229',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 7040 5139',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2185',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0055',
    'FCLT_NM': '샘터공원',
    'LAT': 37.561546,
    'LOT': 127.15907,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '',
    'LOTNO_ADDR': '서울특별시 강동구 고덕동 287',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 6988 5140',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2186',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0056',
    'FCLT_NM': '방죽공원',
    'LAT': 37.558132,
    'LOT': 127.15808,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '서울특별시 강동구 고덕로 295-45',
    'LOTNO_ADDR': '서울특별시 강동구 고덕동 296',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 6980 5103',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2139',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0009',
    'FCLT_NM': '늘벗근린공원',
    'LAT': 37.48957,
    'LOT': 127.05716,
    'BLDN_CLNY_YN': '',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '',
    'LOTNO_ADDR': '서울특별시 강남구 대치동 501',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 6085 4346',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2188',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0058',
    'FCLT_NM': '일자산공원',
    'LAT': 37.53302,
    'LOT': 127.15136,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '서울특별시 강동구 동남로 660',
    'LOTNO_ADDR': '서울특별시 강동구 둔촌동 산 125',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 6919 4824',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2192',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0062',
    'FCLT_NM': '상일공원',
    'LAT': 37.54755,
    'LOT': 127.168396,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '서울특별시 강동구 상암로79길 88',
    'LOTNO_ADDR': '서울특별시 강동구 상일동 188',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 7070 4985',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2194',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0064',
    'FCLT_NM': '솜다래공원',
    'LAT': 37.55368,
    'LOT': 127.14127,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '서울특별시 강동구 고덕로38길 8',
    'LOTNO_ADDR': '서울특별시 강동구 암사동 413-4',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 6831 5054',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2196',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0066',
    'FCLT_NM': '암사공원',
    'LAT': 37.556423,
    'LOT': 127.14172,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '서울특별시 강동구 고덕로 131',
    'LOTNO_ADDR': '서울특별시 강동구 암사동 414-20',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 6835 5084',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2197',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0067',
    'FCLT_NM': '오동근린공원',
    'LAT': 37.629242,
    'LOT': 127.03305,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '',
    'LOTNO_ADDR': '서울특별시 강북구 번동 산 20-1',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 5879 5896',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2198',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0068',
    'FCLT_NM': '솔밭근린공원',
    'LAT': 37.65296,
    'LOT': 127.0119,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '서울특별시 강북구 삼양로 561',
    'LOTNO_ADDR': '서울특별시 강북구 우이동 80',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 5694 6160',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2199',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0069',
    'FCLT_NM': '공암나루',
    'LAT': 37.569897,
    'LOT': 126.85034,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '서울특별시 강서구 허준로5길 15',
    'LOTNO_ADDR': '서울특별시 강서구 가양동 1459-9',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 4262 5247',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2210',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0080',
    'FCLT_NM': '서울식물원',
    'LAT': 37.568172,
    'LOT': 126.832985,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '',
    'LOTNO_ADDR': '서울특별시 강서구 마곡동 812',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 4109 5229',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2213',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0083',
    'FCLT_NM': '방화근린공원',
    'LAT': 37.581966,
    'LOT': 126.81326,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '',
    'LOTNO_ADDR': '서울특별시 강서구 방화동 855',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 3936 5384',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'B0002',
    'FCLT_NM': '대치2단지상가',
    'LAT': 37.493477,
    'LOT': 127.07579,
    'BLDN_CLNY_YN': 'BG_AB',
    'FCLT_USG_SE': 'FU_BA',
    'RDN_ADDR': '서울특별시 강남구 개포로109길 9',
    'LOTNO_ADDR': '서울특별시 강남구 개포동 12',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 6250 4388',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '3',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'B0003',
    'FCLT_NM': '로즈데일오피스텔',
    'LAT': 37.487328,
    'LOT': 127.10314,
    'BLDN_CLNY_YN': 'BG_AB',
    'FCLT_USG_SE': 'FU_BA',
    'RDN_ADDR': '서울특별시 강남구 광평로 280',
    'LOTNO_ADDR': '서울특별시 강남구 수서동 724',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 6491 4319',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '602',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'B0602',
    'FCLT_NM': '김세중미술관',
    'LAT': 37.542038,
    'LOT': 126.963875,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BC',
    'RDN_ADDR': '서울특별시 용산구 효창원로70길 35',
    'LOTNO_ADDR': '서울특별시 용산구 효창동 5-390',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 5263 4932',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '8',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'B0008',
    'FCLT_NM': '롯데백화점 강남점',
    'LAT': 37.49706,
    'LOT': 127.0536,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BA',
    'RDN_ADDR': '서울특별시 강남구 도곡로 401',
    'LOTNO_ADDR': '서울특별시 강남구 대치동 937',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 6054 4429',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '4',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'B0004',
    'FCLT_NM': '수서종합상가',
    'LAT': 37.49027,
    'LOT': 127.10109,
    'BLDN_CLNY_YN': 'BG_AB',
    'FCLT_USG_SE': 'FU_BA',
    'RDN_ADDR': '서울특별시 강남구 광평로51길 49',
    'LOTNO_ADDR': '서울특별시 강남구 수서동 707',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 6473 4352',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '7',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'B0007',
    'FCLT_NM': '역삼서해더블루',
    'LAT': 37.493,
    'LOT': 127.039116,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BA',
    'RDN_ADDR': '서울특별시 강남구 논현로63길 16',
    'LOTNO_ADDR': '서울특별시 강남구 역삼동 796-29',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 5925 4384',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '55',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'B0055',
    'FCLT_NM': '이마트 가양점',
    'LAT': 37.557953,
    'LOT': 126.862274,
    'BLDN_CLNY_YN': 'BG_AB',
    'FCLT_USG_SE': 'FU_BA',
    'RDN_ADDR': '서울특별시 강서구 양천로 559',
    'LOTNO_ADDR': '서울특별시 강서구 가양동 449-19',
    'ETC': '폐점',
    'NTN_BRNCH_NO': '다사 4367 5114',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '10',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'B0010',
    'FCLT_NM': '신원아침도시마인상가',
    'LAT': 37.52646,
    'LOT': 127.049675,
    'BLDN_CLNY_YN': 'BG_AB',
    'FCLT_USG_SE': 'FU_BA',
    'RDN_ADDR': '서울특별시 강남구 도산대로85길 30',
    'LOTNO_ADDR': '서울특별시 강남구 청담동 122-35',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 6020 4755',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '11',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'B0011',
    'FCLT_NM': '한보종합상가(미도상가)',
    'LAT': 37.49477,
    'LOT': 127.06656,
    'BLDN_CLNY_YN': 'BG_AB',
    'FCLT_USG_SE': 'FU_BA',
    'RDN_ADDR': '서울특별시 강남구 삼성로 150',
    'LOTNO_ADDR': '서울특별시 강남구 대치동 511',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 6168 4403',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '59',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'B0059',
    'FCLT_NM': '강서뉴타워',
    'LAT': 37.539104,
    'LOT': 126.83542,
    'BLDN_CLNY_YN': 'BG_AB',
    'FCLT_USG_SE': 'FU_BA',
    'RDN_ADDR': '서울특별시 강서구 화곡로18길 24',
    'LOTNO_ADDR': '서울특별시 강서구 화곡동 1071-19',
    'ETC': '공사중',
    'NTN_BRNCH_NO': '다사 4128 4907',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '12',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'B0012',
    'FCLT_NM': '삼성동 신도브래뉴주상 복합상가',
    'LAT': 37.510387,
    'LOT': 127.053406,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BA',
    'RDN_ADDR': '서울특별시 강남구 삼성로103길 12',
    'LOTNO_ADDR': '서울특별시 강남구 삼성동 121-38',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 6053 4577',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '15',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'B0015',
    'FCLT_NM': '금강쇼핑센타',
    'LAT': 37.53037,
    'LOT': 127.0298,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BA',
    'RDN_ADDR': '서울특별시 강남구 압구정로 201',
    'LOTNO_ADDR': '서울특별시 강남구 압구정동 458',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 5845 4799',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2218',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0088',
    'FCLT_NM': '우장근린공원',
    'LAT': 37.554943,
    'LOT': 126.84458,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '서울특별시 강서구 우장산로10길 25-19',
    'LOTNO_ADDR': '서울특별시 강서구 화곡동 산 60-1',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 4210 5082',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2221',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0091',
    'FCLT_NM': '신림근린공원',
    'LAT': 37.481503,
    'LOT': 126.9175,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '서울특별시 관악구 난곡로64길 47',
    'LOTNO_ADDR': '서울특별시 관악구 신림동 1707-1',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 4849 4263',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2222',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0092',
    'FCLT_NM': '장군봉근린공원',
    'LAT': 37.478657,
    'LOT': 126.93909,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '서울특별시 관악구 장군봉길 100',
    'LOTNO_ADDR': '서울특별시 관악구 신림동 산 1-1',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 5040 4230',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2223',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0093',
    'FCLT_NM': '온수근린공원',
    'LAT': 37.502087,
    'LOT': 126.83835,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '',
    'LOTNO_ADDR': '서울특별시 구로구 개봉동 45-2',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 4151 4496',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2224',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0094',
    'FCLT_NM': '개웅산근린공원',
    'LAT': 37.486908,
    'LOT': 126.84712,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '',
    'LOTNO_ADDR': '서울특별시 구로구 개봉동 산53-3',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 4228 4327',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2226',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0096',
    'FCLT_NM': '계남근린공원',
    'LAT': 37.509285,
    'LOT': 126.85012,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '',
    'LOTNO_ADDR': '서울특별시 구로구 고척동 산 8',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 4256 4575',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2227',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0097',
    'FCLT_NM': '고척근린공원',
    'LAT': 37.505936,
    'LOT': 126.852005,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '',
    'LOTNO_ADDR': '서울특별시 구로구 고척동 산 9-14',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 4272 4538',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2229',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0099',
    'FCLT_NM': '테크노근린공원',
    'LAT': 37.507988,
    'LOT': 126.89093,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '서울특별시 구로구 새말로 107-32',
    'LOTNO_ADDR': '서울특별시 구로구 구로동 3-33',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 4616 4558',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '16',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'B0016',
    'FCLT_NM': '갤러리아명품관(서관)',
    'LAT': 37.52856,
    'LOT': 127.040054,
    'BLDN_CLNY_YN': 'BG_AB',
    'FCLT_USG_SE': 'FU_BA',
    'RDN_ADDR': '서울특별시 강남구 압구정로 343',
    'LOTNO_ADDR': '서울특별시 강남구 압구정동 494',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 5936 4779',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '17',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'B0017',
    'FCLT_NM': '갤러리아명품관(동관)',
    'LAT': 37.52808,
    'LOT': 127.04157,
    'BLDN_CLNY_YN': 'BG_AB',
    'FCLT_USG_SE': 'FU_BA',
    'RDN_ADDR': '서울특별시 강남구 압구정로 407',
    'LOTNO_ADDR': '서울특별시 강남구 압구정동 515',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 5949 4774',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '22',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'B0022',
    'FCLT_NM': '(주)한솔필리아 (이마트역삼점)',
    'LAT': 37.499218,
    'LOT': 127.04844,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BA',
    'RDN_ADDR': '서울특별시 강남구 역삼로 310',
    'LOTNO_ADDR': '서울특별시 강남구 역삼동 755',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 6008 4453',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '80',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'B0080',
    'FCLT_NM': '자양종합상가',
    'LAT': 37.531994,
    'LOT': 127.07644,
    'BLDN_CLNY_YN': 'BG_AB',
    'FCLT_USG_SE': 'FU_BA',
    'RDN_ADDR': '서울특별시 광진구 자양번영로6길 20',
    'LOTNO_ADDR': '서울특별시 광진구 자양동 602',
    'ETC': '건물 노후화로인한 폐쇄',
    'NTN_BRNCH_NO': '다사 6257 4816',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '24',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'B0024',
    'FCLT_NM': '현대백화점 무역센타(한무쇼핑㈜)',
    'LAT': 37.508595,
    'LOT': 127.059715,
    'BLDN_CLNY_YN': 'BG_AB',
    'FCLT_USG_SE': 'FU_BA',
    'RDN_ADDR': '서울특별시 강남구 테헤란로 517',
    'LOTNO_ADDR': '서울특별시 강남구 삼성동 159-7',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 6108 4557',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '82',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'B0082',
    'FCLT_NM': '롯데마트 구로점',
    'LAT': 37.498234,
    'LOT': 126.87266,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BA',
    'RDN_ADDR': '서울특별시 구로구 경인로 482',
    'LOTNO_ADDR': '서울특별시 구로구 구로동 636-89',
    'ETC': '폐점',
    'NTN_BRNCH_NO': '다사 4454 4451',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '26',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'B0026',
    'FCLT_NM': '한국도심공항몰',
    'LAT': 37.509644,
    'LOT': 127.05943,
    'BLDN_CLNY_YN': 'BG_AB',
    'FCLT_USG_SE': 'FU_BA',
    'RDN_ADDR': '서울특별시 강남구 테헤란로87길 21',
    'LOTNO_ADDR': '서울특별시 강남구 삼성동 159-6',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 6106 4568',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2232',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0102',
    'FCLT_NM': '천왕근린공원(시)',
    'LAT': 37.479607,
    'LOT': 126.83104,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '',
    'LOTNO_ADDR': '서울특별시 구로구 항동 149-1',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 4085 4247',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2233',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0103',
    'FCLT_NM': '푸른수목원',
    'LAT': 37.48354,
    'LOT': 126.82405,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '',
    'LOTNO_ADDR': '서울특별시 구로구 항동 31',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 4023 4291',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2216',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0086',
    'FCLT_NM': '봉제산',
    'LAT': 37.5398,
    'LOT': 126.8591,
    'BLDN_CLNY_YN': '',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '',
    'LOTNO_ADDR': '서울특별시 강서구 화곡동 산 5-6',
    'ETC': '',
    'NTN_BRNCH_NO': '다사 4338 4913',
    'DATA_CRTR_DD': '2022-12-07 00:00:00.0'},
   {'ID': '2235',
    'NEW_ADDR_ID': '',
    'FCLT_ID': 'P0105',
    'FCLT_NM': '감로천생태공원',
    'LAT': 37.469616,
    'LOT': 126.90791,
    'BLDN_CLNY_YN': 'BG_AA',
    'FCLT_USG_SE': 'FU_BI',
    'RDN_ADDR': '서울특별시 금천구 독산로54길 188',
    'LOTNO_ADDR': '서울특별시 금천구 독산동 373',

In [22]:
temp = []
for d in data['tbEntranceItem']['row']:
  temp.append(d)
pd_data = pd.DataFrame(temp)
pd_data

,ID,NEW_ADDR_ID,FCLT_ID,FCLT_NM,LAT,LOT,BLDN_CLNY_YN,FCLT_USG_SE,RDN_ADDR,LOTNO_ADDR,ETC,NTN_BRNCH_NO,DATA_CRTR_DD
0,3007,,P0877,꿈동산어린이공원,37.650288,127.036860,BG_AA,FU_BI,서울특별시 도봉구 도봉로110나길 99,서울특별시 도봉구 창동 663-1,,다사 5914 6130,2022-12-07 00:00:00.0
1,3008,,P0878,미화어린이공원,37.654945,127.039690,BG_AA,FU_BI,서울특별시 도봉구 도봉로 564,서울특별시 도봉구 창동 715-17,,다사 5939 6181,2022-12-07 00:00:00.0
2,3009,,P0879,꿈동산어린이공원,37.573290,127.045840,BG_AA,FU_BI,서울특별시 동대문구 황물로 42,서울특별시 동대문구 답십리동 1002-1,,다사 5989 5275,2022-12-07 00:00:00.0
3,3010,,P0880,새움어린이공원,37.570760,127.048676,BG_AA,FU_BI,서울특별시 동대문구 천호대로55길 11,서울특별시 동대문구 답십리동 1009-1,,다사 6014 5247,2022-12-07 00:00:00.0
4,3012,,P0882,동산어린이공원,37.566967,127.057540,BG_AA,FU_BI,서울특별시 동대문구 전농로2나길 7,서울특별시 동대문구 답십리동 998-1,,다사 6092 5204,2022-12-07 00:00:00.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,46,,B0046,성북프라자,37.621567,127.026460,BG_AB,FU_BA,서울특별시 강북구 도봉로33길 18,서울특별시 강북구 미아동 318-5,,다사 5821 5811,2022-12-07 00:00:00.0
96,47,,B0047,수유시장,37.630783,127.022950,BG_AB,FU_BA,서울특별시 강북구 도봉로67길 18,서울특별시 강북구 수유동 54-5,,다사 5790 5914,2022-12-07 00:00:00.0
97,48,,B0048,롯데마트 삼양점,37.625576,127.017715,BG_AA,FU_BA,서울특별시 강북구 삼양로 247,서울특별시 강북구 미아동 1359,,다사 5744 5856,2022-12-07 00:00:00.0
98,49,,B0049,동북프라자,37.620247,127.018790,BG_AB,FU_BA,서울특별시 강북구 솔샘로 233,서울특별시 강북구 미아동 701-3,,다사 5753 5797,2022-12-07 00:00:00.0
99,50,,B0050,NC백화점 강서점,37.559963,126.840350,BG_AA,FU_BA,서울특별시 강서구 강서로56길 17,서울특별시 강서구 등촌동 689,,다사 4173 5138,2022-12-07 00:00:00.0

In [24]:
import folium
from folium.plugins import MarkerCluster

rest_map = folium.Map(location=[37.650288, 127.036860],
                      zoom_start=10,
                      zoom_control=False,
                      control_scale=True)

mc = MarkerCluster().add_to(rest_map)

for n, row in pd_data.iterrows():
  folium.Marker(location=[row['LAT'], row['LOT']],
                popup=folium.Popup(row['FCLT_NM'], max_width=200)).add_to(mc)

rest_map